order/urls.py
from django.urls import path

from order import views

app_name = 'order'
urlpatterns = [
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add-to-cart'),
    path('cart-view/', views.cart_view, name='cart'),
    path('remove-item/<int:pk>/', views.remove_item_from_cart, name='remove-item'),
    path('increase-quantity/<int:pk>/', views.increase_cart, name='increase-quantity'),
    path('decrease-quantity/<int:pk>/', views.decrease_cart, name='decrease-quantity'),
]

pyshops/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('store.urls')),
    path('order/', include('order.urls')),
    path('payment/', include('payment.urls')),


]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store import views

app_name = 'store'
urlpatterns = [
    path('', views.HomeListView.as_view(), name='index'),
    path('product/<slug>', views.ProductDetailView.as_view(), name='product-details'),
]

store/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify

from django.contrib.auth import get_user_model

User = get_user_model()

class Category(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)
    image = models.ImageField(upload_to='category', blank=True, null=True)
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created', ]
        verbose_name_plural = 'categories'


class Product(models.Model):
    name = models.CharField(max_length=250, blank=False, null=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    short_desc = models.CharField(max_length=255, verbose_name='Short Description')
    long_desc = models.CharField(max_length=1000, verbose_name='Long Description')
    image = models.ImageField(upload_to='products', blank=False, null=False)
    price = models.FloatField()
    old_price = models.FloatField(default=0.00, blank=True, null=True)
    is_stock = models.BooleanField(default=True)
    slug = models.SlugField(unique=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created']

    def get_product_url(self):
        return reverse('store:product-details', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.FileField(upload_to='product_gallery')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product.name)


class VariationManager(models.Manager):
    def sizes(self):
        return super(VariationManager, self).filter(variation='size')

    def colors(self):
        return super(VariationManager, self).filter(variation='color')


VARIATIONS_TYPE = (
    ('size', 'size'),
    ('color', 'color'),

)


class VariationValue(models.Model):
    variation = models.CharField(max_length=100, choices=VARIATIONS_TYPE)
    name = models.CharField(max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='variation_image', blank=True, null=True)

    objects = VariationManager()

    def __str__(self):
        return self.name


class Banner(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='banner')
    image = models.ImageField(upload_to='banner')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name


User = get_user_model()


class MyLogo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='logo')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.image)


class MyFavicon(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='logo')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.image)

store/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, TemplateView

# Product models
from store.models import Product, Category, ProductImages, Banner


class HomeListView(TemplateView):

    def get(self, request, *args, **kwargs):
        products = Product.objects.all().order_by('-id')
        banners = Banner.objects.filter(is_active=True).order_by('-id')[0:3]

        context = {
            'products': products,
            'banners': banners,
        }
        return render(request, 'store/index.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == 'post' or request.method == 'POST':
            search_product = request.POST.get('search_product')
            products = Product.objects.filter(name__icontains=search_product).order_by('-id')

            context = {
                'products': products,
            }
            return render(request, 'store/index.html', context)

    # model = Product
    # template_name = 'store/index.html'
    # context_object_name = 'products'
    #
    # def get_context_data(self, *args, **kwargs):
    #     context = super().get_context_data(*args, **kwargs)
    #     context['banners'] = Banner.objects.filter(is_active=True).order_by('-id')[0:3]
    #     return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product.html'
    context_object_name = 'item'

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex['product_gallery_images'] = ProductImages.objects.filter(product=self.object.id)

        return contex

# def product_details(request, pk):
#     item = Product.objects.get(id = pk)
#     gallery_photos = ProductImages.objects.filter(product=item).order_by('-created')
#     context ={
#         'item' : item
#          'gallery_photos' : gallery_photos
#     }
#     return render(request, 'store/product.html', context)

templates/store/cart.html
{% extends 'base.html' %}
{% block title %} Cart Page{% endblock title %}
{% block body %}

<main class="main">
    <div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">Shopping Cart<span>Shop</span></h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Shop</a></li>
                <li class="breadcrumb-item active" aria-current="page">Shopping Cart</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="cart">
            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        <table class="table table-cart table-mobile">
                            <thead>
                            <tr>
                                <th>Product</th>
                                <th>Color</th>
                                <th>Size</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for cart in carts %}
                            <tr>
                                <td class="product-col">
                                    <div class="product">
                                        <figure class="product-media">
                                            <a href="#">
                                                <img src="{{ cart.item.image.url }}"
                                                     alt="Product image">
                                            </a>
                                        </figure>

                                        <h3 class="product-title">
                                            <a href="#">{{ cart.item.name }}</a>
                                        </h3><!-- End .product-title -->
                                    </div><!-- End .product -->
                                </td>
                                <td class="price-col">{{ cart.size }}</td>
                                <td class="price-col">{{ cart.color }}</td>

                                <td class="price-col">
                                    {% if cart.variation_single_price %}
                                    ${{ cart.variation_single_price }}
                                    {% else %}
                                    ${{ cart.item.price }}
                                    {% endif %}
                                </td>

                                <td class="quantity-col">
                                    <div class="cart-product-quantity">
                                        <!--                                        <input type="number" class="form-control" value="{{ cart.quantity }}" min="1" max="10" step="1"-->
                                        <!--                                               data-decimals="0" required>-->
                                        <a href="{% url 'order:decrease-quantity' pk=cart.item.pk %}" class="mr-2"><span
                                                class="badge badge-light"><i class="las la-minus"></i></span></a>
                                        <span>{{ cart.quantity }}</span>
                                        <a href="{% url 'order:increase-quantity' pk=cart.item.pk %}" class="mr-2"><span
                                                class="badge badge-light"><i class="las la-plus"></i></span></a>
                                    </div><!-- End .cart-product-quantity -->
                                </td>
                                <td class="total-col">
                                    {% if cart.variation_total %}
                                    ${{ cart.variation_total }}
                                    {% else %}
                                    ${{ cart.get_total }}
                                    {% endif %}

                                </td>
                                <td class="remove-col">
                                    <a href="{% url 'order:remove-item' pk=cart.item.pk %}">
                                        <button class="btn-remove"><i class="icon-close"></i></button>
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table><!-- End .table table-wishlist -->

                        <div class="cart-bottom">
                            <div class="cart-discount">
                                <form action="" method="post">
                                    <div class="input-group">
                                        {% csrf_token %}
                                        {{ coupon_form }}
                                        <div class="input-group-append">
                                            <button class="btn btn-outline-primary-2" type="submit"><i
                                                    class="icon-long-arrow-right"></i></button>
                                        </div><!-- .End .input-group-append -->
                                    </div><!-- End .input-group -->
                                </form>
                            </div><!-- End .cart-discount -->

                            <a href="#" class="btn btn-outline-dark-2"><span>UPDATE CART</span><i
                                    class="icon-refresh"></i></a>
                        </div><!-- End .cart-bottom -->
                    </div><!-- End .col-lg-9 -->
                    <aside class="col-lg-3">
                        <div class="summary summary-cart">
                            <h3 class="summary-title">Cart Total</h3><!-- End .summary-title -->

                            <table class="table table-summary">
                                <tbody>
                                <tr class="summary-subtotal">
                                    <td>Subtotal:</td>
                                    <td>${{ order.get_totals }}</td>
                                </tr><!-- End .summary-subtotal -->
                                <tr class="summary-shipping">
                                    <td>Shipping:</td>
                                    <td>&nbsp;</td>
                                </tr>

                                <tr class="summary-shipping-row">
                                    <td>
                                        <div class="custom-control custom-radio">
                                            <input type="radio" id="free-shipping" name="shipping"
                                                   class="custom-control-input">
                                            <label class="custom-control-label" for="free-shipping">Free
                                                Shipping</label>
                                        </div><!-- End .custom-control -->
                                    </td>
                                    <td>$0.00</td>
                                </tr><!-- End .summary-shipping-row -->

                                <tr class="summary-shipping-row">
                                    <td>
                                        <div class="custom-control custom-radio">
                                            <input type="radio" id="standart-shipping" name="shipping"
                                                   class="custom-control-input">
                                            <label class="custom-control-label"
                                                   for="standart-shipping">Standart:</label>
                                        </div><!-- End .custom-control -->
                                    </td>
                                    <td>$10.00</td>
                                </tr><!-- End .summary-shipping-row -->

                                <tr class="summary-shipping-row">
                                    <td>
                                        <div class="custom-control custom-radio">
                                            <input type="radio" id="express-shipping" name="shipping"
                                                   class="custom-control-input">
                                            <label class="custom-control-label" for="express-shipping">Express:</label>
                                        </div><!-- End .custom-control -->
                                    </td>
                                    <td>$20.00</td>
                                </tr><!-- End .summary-shipping-row -->

                                <tr class="summary-shipping-estimate">
                                    <td>Estimate for Your Country<br> <a href="dashboard.html">Change address</a></td>
                                    <td>&nbsp;</td>
                                </tr><!-- End .summary-shipping-estimate -->

                                <tr class="summary-total">
                                    <td>Total:</td>
                                    <td>
                                        {% if after_discount_total_price %}
                                        ${{ after_discount_total_price }}
                                        {% else %}
                                        ${{ order.get_totals }}
                                        {% endif %}


                                    </td>
                                </tr><!-- End .summary-total -->
                                </tbody>
                            </table><!-- End .table table-summary -->

                            <a href="{% url 'checkout' %}" class="btn btn-outline-primary-2 btn-order btn-block">PROCEED TO
                                CHECKOUT</a>
                        </div><!-- End .summary -->

                        <a href="category.html"
                           class="btn btn-outline-dark-2 btn-block mb-3"><span>CONTINUE SHOPPING</span><i
                                class="icon-refresh"></i></a>
                    </aside><!-- End .col-lg-3 -->
                </div><!-- End .row -->
            </div><!-- End .container -->
        </div><!-- End .cart -->
    </div><!-- End .page-content -->
</main><!-- End .main -->

{% endblock %}

templates/store/checkout.html
{% extends 'base.html' %}
{% block title %} Checkout Page{% endblock title %}
{% block body %}

<main class="main">
    <div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        <div class="container">
            <h1 class="page-title">Checkout<span>Shop</span></h1>
        </div><!-- End .container -->
    </div><!-- End .page-header -->
    <nav aria-label="breadcrumb" class="breadcrumb-nav">
        <div class="container">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Shop</a></li>
                <li class="breadcrumb-item active" aria-current="page">Checkout</li>
            </ol>
        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="checkout">
            <div class="container">
                <div class="checkout-discount">
                    <form action="#">
                        <input type="text" class="form-control" required id="checkout-discount-input">
                        <label for="checkout-discount-input" class="text-truncate">Have a coupon? <span>Click here to enter your code</span></label>
                    </form>
                </div><!-- End .checkout-discount -->
                <form action="" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-9">
                            <h2 class="checkout-title">Billing Details</h2><!-- End .checkout-title -->

                            {{ billing_address.as_p }}
                            <!--                            <label>Order notes (optional)</label>-->
                            <!--                            <textarea class="form-control" cols="30" rows="4"-->
                            <!--                                      placeholder="Notes about your order, e.g. special notes for delivery"></textarea>-->
                        </div><!-- End .col-lg-9 -->
                        <aside class="col-lg-3">
                            <div class="summary">
                                <h3 class="summary-title">Your Order</h3><!-- End .summary-title -->

                                <table class="table table-summary">
                                    <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Total</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    {% for item in order_item %}
                                    <tr>
                                        <td><a href="#">{{ item.item.name }}</a></td>
                                        {% if item.get_total %}
                                        <td>${{ item.get_total }}</td>
                                        {% elif item.variation_single_price %}
                                        <td>${{ item.variation_single_price }}</td>
                                        {% elif item.variation_total %}
                                        <td>${{ item.variation_total }}</td>
                                        {% endif %}
                                    </tr>
                                    {% endfor %}

                                    <tr class="summary-subtotal">
                                        <td>Subtotal:</td>
                                        <td>${{ order_total }}</td>
                                    </tr><!-- End .summary-subtotal -->
                                    <tr>
                                        <td>Shipping:</td>
                                        <td>Free shipping</td>
                                    </tr>
                                    <tr class="summary-total">
                                        <td>Total:</td>
                                        <td>${{ order_total }}</td>
                                    </tr><!-- End .summary-total -->
                                    </tbody>
                                </table><!-- End .table table-summary -->

                                <div class="accordion-summary" id="accordion-payment">
                                    <div class="card">
                                        {% if pay_meth %}
                                            <div id="paypal-button-container"></div>
                                        {% else %}
                                            {{ payment_method.as_p }}
                                        {% endif %}
                                        <br>
                                    </div>
                                    <button type="submit" class="btn btn-outline-primary-2 btn-order btn-block">
                                        <span class="btn-text">Place Order</span>
                                        <span class="btn-hover-text">Proceed to Checkout</span>
                                    </button>
                                </div><!-- End .summary -->
                        </aside><!-- End .col-lg-3 -->
                    </div><!-- End .row -->
                </form>
            </div><!-- End .container -->
        </div><!-- End .checkout -->
    </div><!-- End .page-content -->
</main><!-- End .main -->
{% endblock %}

{% block paypal %}

<script src="https://www.paypal.com/sdk/js?client-id={{paypal_client_id}}&currency=USD"></script>

<script>

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
                }
            }
        }
        return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    var url = "{% url 'paypal_payment' %}";




    paypal.Buttons({
        createOrder: function(data, action){
            return action.order.create({
                purchase_units: [{
                    amount: {
                        value: {{order_total}}
                    }
                }]
            });
        },

        onApprove: (data, actions) => {
            return actions.order.capture().then(function(details) {

            console.log(details);
            sendData();
            function sendData(){
                fetch(url, {
                    method: "POST",
                    headers: {
                        'content-type': "application/json",
                        'X-CSRFToken' : csrftoken
                    },
                    body : JSON.stringify({
                        'order_id' : details.id,
                        'payment_id' : details.payer.payer_id,
                        'status' : details.status,
                    }),
                })
            }
            window.location.href = "{% url 'store:index' %}"
            });
        }

    }).render('#paypal-button-container');

</script>

{% endblock paypal %}